[workspace]
resolver = "2"
members = [
    "crates/sprout-cli",
    "crates/sprout-core",
    "crates/sprout-preload",
    "crates/sprout-ptrace",
]

[workspace.package]
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sprout-os/sprout"
homepage = "https://github.com/sprout-os/sprout"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
cc = "1.1"
nix = { version = "0.29", features = ["process", "ptrace", "signal", "fs"] }
thiserror = "1.0"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
