[package]
name = "sprout-cli"
version = "0.5.1"
description = "Rootless glibc Linux runtime for Android — proot-compatible launcher (LD_PRELOAD fast path, ptrace fallback)"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "sprout"
path = "src/main.rs"

[dependencies]
sprout-core = { path = "../sprout-core" }
sprout-preload = { path = "../sprout-preload" }
sprout-ptrace = { path = "../sprout-ptrace" }
clap.workspace = true
anyhow.workspace = true
libc.workspace = true
tar.workspace = true
flate2.workspace = true
xz2.workspace = true
bzip2.workspace = true
